# Generated by Django 5.0.3 on 2024-03-20 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_user_company_user_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-dt',), 'verbose_name': 'Заказ', 'verbose_name_plural': 'Список заказов'},
        ),
    ]
